import React, { useState, useEffect, useRef } from 'react';
import { useParams, useSearchParams, useNavigate } from 'react-router';
import { 
  Brain, 
  CheckCircle2, 
  XCircle, 
  Activity, 
  MapPin, 
  FileText, 
  Download,
  AlertCircle,
  Home,
  Loader2,
  ChevronRight
} from 'lucide-react';
import { Button } from '../components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../components/ui/card';
import { Progress } from '../components/ui/progress';
import { Badge } from '../components/ui/badge';
import { Separator } from '../components/ui/separator';
import { toast } from 'sonner';
import { projectId, publicAnonKey } from '/utils/supabase/info';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export default function Analysis() {
  const { scanId } = useParams();
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const reportRef = useRef<HTMLDivElement>(null);

  const patientName = searchParams.get('name') || 'Unknown Patient';
  const patientAge = searchParams.get('age') || 'N/A';
  const patientGender = searchParams.get('gender') || 'N/A';

  const [currentStage, setCurrentStage] = useState(0);
  const [loading, setLoading] = useState(false);
  
  // Stage data
  const [detectionResult, setDetectionResult] = useState<any>(null);
  const [classificationResult, setClassificationResult] = useState<any>(null);
  const [gradcamData, setGradcamData] = useState<any>(null);
  const [hospitals, setHospitals] = useState<any[]>([]);
  const [gradcamImage, setGradcamImage] = useState<string>('');

  const stages = [
    { id: 0, name: 'Stage 1: Tumor Detection', icon: Brain, color: 'blue' },
    { id: 1, name: 'Stage 2: Classification', icon: Activity, color: 'purple' },
    { id: 2, name: 'GradCAM Analysis', icon: Brain, color: 'green' },
    { id: 3, name: 'Nearby Hospitals', icon: MapPin, color: 'orange' },
    { id: 4, name: 'Report Generation', icon: FileText, color: 'red' },
  ];

  useEffect(() => {
    if (scanId && currentStage === 0 && !detectionResult) {
      runStage1Detection();
    }
  }, [scanId, currentStage]);

  const runStage1Detection = async () => {
    setLoading(true);
    toast.info('Running Stage 1: Tumor Detection...');

    try {
      const response = await fetch(
        `https://tbxyjwpcrzbdtuuraowe.supabase.co/functions/v1/make-server-cfefc943/detect-tumor`,
        {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${publicAnonKey}`,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({ scanId }),
        }
      );

      const data = await response.json();

      if (!response.ok) {
        console.error('Detection failed:', data);
        toast.error(data.error || 'Failed to detect tumor');
        return;
      }

      setDetectionResult(data);
      
      if (data.tumorDetected) {
        toast.success(`Tumor detected with ${(parseFloat(data.confidence) * 100).toFixed(0)}% confidence`);
      } else {
        toast.success('No tumor detected');
      }
    } catch (error) {
      console.error('Error during tumor detection:', error);
      toast.error('Failed to complete tumor detection');
    } finally {
      setLoading(false);
    }
  };

  const runStage2Classification = async () => {
    if (!detectionResult?.tumorDetected) {
      toast.error('No tumor detected. Classification not required.');
      return;
    }

    setLoading(true);
    setCurrentStage(1);
    toast.info('Running Stage 2: Tumor Classification...');

    try {
      const response = await fetch(
        `https://tbxyjwpcrzbdtuuraowe.supabase.co/functions/v1/make-server-cfefc943/classify-tumor`,
        {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${publicAnonKey}`,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({ scanId }),
        }
      );

      const data = await response.json();

      if (!response.ok) {
        console.error('Classification failed:', data);
        toast.error(data.error || 'Failed to classify tumor');
        return;
      }

      setClassificationResult(data);
      toast.success(`Tumor classified as ${data.tumorType}`);
    } catch (error) {
      console.error('Error during tumor classification:', error);
      toast.error('Failed to complete tumor classification');
    } finally {
      setLoading(false);
    }
  };

  const generateGradCAM = async () => {
    setLoading(true);
    setCurrentStage(2);
    toast.info('Generating GradCAM visualization...');

    try {
      // Simulate GradCAM generation with a colored overlay
      // In production, this would be generated by your ML model
      const canvas = document.createElement('canvas');
      canvas.width = 400;
      canvas.height = 400;
      const ctx = canvas.getContext('2d');
      
      if (ctx) {
        // Create a heatmap-like gradient
        const gradient = ctx.createRadialGradient(200, 200, 0, 200, 200, 200);
        gradient.addColorStop(0, 'rgba(255, 0, 0, 0.8)');
        gradient.addColorStop(0.5, 'rgba(255, 255, 0, 0.5)');
        gradient.addColorStop(1, 'rgba(0, 0, 255, 0.1)');
        
        ctx.fillStyle = gradient;
        ctx.fillRect(0, 0, 400, 400);
        
        // Add some noise for realism
        for (let i = 0; i < 100; i++) {
          const x = Math.random() * 400;
          const y = Math.random() * 400;
          const radius = Math.random() * 20;
          const intensity = Math.random();
          
          ctx.fillStyle = `rgba(255, ${Math.floor(intensity * 255)}, 0, ${intensity * 0.3})`;
          ctx.beginPath();
          ctx.arc(x, y, radius, 0, Math.PI * 2);
          ctx.fill();
        }
      }
      
      const imageData = canvas.toDataURL('image/png');
      setGradcamImage(imageData);

      const response = await fetch(
        `https://tbxyjwpcrzbdtuuraowe.supabase.co/functions/v1/make-server-cfefc943/generate-gradcam`,
        {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${publicAnonKey}`,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({ scanId, imageData }),
        }
      );

      const data = await response.json();

      if (!response.ok) {
        console.error('GradCAM generation failed:', data);
        toast.error(data.error || 'Failed to generate GradCAM');
        return;
      }

      setGradcamData(data);
      toast.success('GradCAM visualization generated');
    } catch (error) {
      console.error('Error generating GradCAM:', error);
      toast.error('Failed to generate GradCAM');
    } finally {
      setLoading(false);
    }
  };

  const findNearbyHospitals = async () => {
    setLoading(true);
    setCurrentStage(3);
    toast.info('Finding nearby hospitals...');

    try {
      // Get user's location
      navigator.geolocation.getCurrentPosition(
        async (position) => {
          const { latitude, longitude } = position.coords;

          const response = await fetch(
            `https://tbxyjwpcrzbdtuuraowe.supabase.co/functions/v1/make-server-cfefc943/nearby-hospitals`,
            {
              method: 'POST',
              headers: {
                'Authorization': `Bearer ${publicAnonKey}`,
                'Content-Type': 'application/json',
              },
              body: JSON.stringify({ latitude, longitude }),
            }
          );

          const data = await response.json();

          if (!response.ok) {
            console.error('Hospital search failed:', data);
            toast.error(data.error || 'Failed to find hospitals');
            return;
          }

          setHospitals(data.hospitals);
          toast.success(`Found ${data.hospitals.length} nearby hospitals`);
          setLoading(false);
        },
        (error) => {
          console.error('Geolocation error:', error);
          toast.error('Unable to get location. Using default coordinates.');
          
          // Fallback to default location
          fetch(
            `https://tbxyjwpcrzbdtuuraowe.supabase.co/functions/v1/make-server-cfefc943/nearby-hospitals`,
            {
              method: 'POST',
              headers: {
                'Authorization': `Bearer ${publicAnonKey}`,
                'Content-Type': 'application/json',
              },
              body: JSON.stringify({ latitude: 40.7128, longitude: -74.0060 }),
            }
          ).then(res => res.json()).then(data => {
            setHospitals(data.hospitals);
            setLoading(false);
          });
        }
      );
    } catch (error) {
      console.error('Error finding hospitals:', error);
      toast.error('Failed to find nearby hospitals');
      setLoading(false);
    }
  };

  const generateReport = async () => {
    setCurrentStage(4);
    toast.info('Generating comprehensive report...');

    try {
      const response = await fetch(
        `https://tbxyjwpcrzbdtuuraowe.supabase.co/functions/v1/make-server-cfefc943/generate-report`,
        {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${publicAnonKey}`,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            scanId,
            patientName,
            patientAge,
            patientGender,
          }),
        }
      );

      const data = await response.json();

      if (!response.ok) {
        console.error('Report generation failed:', data);
        toast.error(data.error || 'Failed to generate report');
        return;
      }

      toast.success('Report generated successfully!');
    } catch (error) {
      console.error('Error generating report:', error);
      toast.error('Failed to generate report');
    }
  };

  const downloadReport = async () => {
    if (!reportRef.current) return;

    toast.info('Preparing PDF download...');

    try {
      const canvas = await html2canvas(reportRef.current, {
        scale: 2,
        backgroundColor: '#ffffff',
      });

      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');
      
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = pdf.internal.pageSize.getHeight();
      const imgWidth = canvas.width;
      const imgHeight = canvas.height;
      const ratio = Math.min(pdfWidth / imgWidth, pdfHeight / imgHeight);
      const imgX = (pdfWidth - imgWidth * ratio) / 2;
      const imgY = 0;

      pdf.addImage(imgData, 'PNG', imgX, imgY, imgWidth * ratio, imgHeight * ratio);
      pdf.save(`brain-tumor-report-${scanId}.pdf`);
      
      toast.success('Report downloaded successfully!');
    } catch (error) {
      console.error('Error downloading report:', error);
      toast.error('Failed to download report');
    }
  };

  const progressPercentage = ((currentStage + 1) / stages.length) * 100;

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-cyan-50">
      {/* Header */}
      <header className="border-b bg-white/80 backdrop-blur-sm sticky top-0 z-50">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="h-10 w-10 rounded-lg bg-gradient-to-br from-blue-600 to-cyan-500 flex items-center justify-center">
                <Brain className="h-6 w-6 text-white" />
              </div>
              <div>
                <h1 className="text-xl font-bold text-gray-900">Analysis in Progress</h1>
                <p className="text-sm text-gray-600">Patient: {patientName}</p>
              </div>
            </div>
            <Button variant="outline" onClick={() => navigate('/')}>
              <Home className="h-4 w-4 mr-2" />
              Home
            </Button>
          </div>
        </div>
      </header>

      <main className="container mx-auto px-4 py-8">
        {/* Progress Indicator */}
        <Card className="mb-8">
          <CardHeader>
            <CardTitle>Analysis Progress</CardTitle>
            <CardDescription>
              {stages[currentStage].name}
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Progress value={progressPercentage} className="mb-4" />
            <div className="flex justify-between items-center">
              {stages.map((stage, index) => {
                const Icon = stage.icon;
                const isComplete = index < currentStage;
                const isCurrent = index === currentStage;
                
                return (
                  <div key={stage.id} className="flex flex-col items-center gap-2">
                    <div
                      className={`h-12 w-12 rounded-full flex items-center justify-center transition-all ${
                        isComplete
                          ? 'bg-green-500 text-white'
                          : isCurrent
                          ? `bg-${stage.color}-500 text-white animate-pulse`
                          : 'bg-gray-200 text-gray-400'
                      }`}
                    >
                      {isComplete ? <CheckCircle2 className="h-6 w-6" /> : <Icon className="h-6 w-6" />}
                    </div>
                    <span className="text-xs text-center max-w-[80px] hidden md:block">
                      {stage.name.split(':')[1] || stage.name}
                    </span>
                  </div>
                );
              })}
            </div>
          </CardContent>
        </Card>

        {/* Patient Information */}
        <Card className="mb-8">
          <CardHeader>
            <CardTitle>Patient Information</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid md:grid-cols-3 gap-4">
              <div>
                <p className="text-sm text-gray-600">Name</p>
                <p className="font-semibold">{patientName}</p>
              </div>
              <div>
                <p className="text-sm text-gray-600">Age</p>
                <p className="font-semibold">{patientAge} years</p>
              </div>
              <div>
                <p className="text-sm text-gray-600">Gender</p>
                <p className="font-semibold">{patientGender}</p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Stage 1: Tumor Detection Results */}
        {detectionResult && (
          <Card className="mb-8 border-blue-200">
            <CardHeader className="bg-blue-50/50">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Brain className="h-5 w-5 text-blue-600" />
                  <CardTitle>Stage 1: Tumor Detection</CardTitle>
                </div>
                <CheckCircle2 className="h-5 w-5 text-green-500" />
              </div>
            </CardHeader>
            <CardContent className="pt-6">
              <div className="flex items-center gap-4 mb-4">
                {detectionResult.tumorDetected ? (
                  <>
                    <AlertCircle className="h-12 w-12 text-red-500" />
                    <div>
                      <p className="text-xl font-bold text-red-600">Tumor Detected</p>
                      <p className="text-sm text-gray-600">
                        Confidence: {(parseFloat(detectionResult.confidence) * 100).toFixed(1)}%
                      </p>
                    </div>
                  </>
                ) : (
                  <>
                    <CheckCircle2 className="h-12 w-12 text-green-500" />
                    <div>
                      <p className="text-xl font-bold text-green-600">No Tumor Detected</p>
                      <p className="text-sm text-gray-600">
                        Confidence: {(parseFloat(detectionResult.confidence) * 100).toFixed(1)}%
                      </p>
                    </div>
                  </>
                )}
              </div>
              
              {detectionResult.tumorDetected && !classificationResult && (
                <Button
                  onClick={runStage2Classification}
                  disabled={loading}
                  className="bg-purple-600 hover:bg-purple-700"
                >
                  {loading ? (
                    <>
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                      Processing...
                    </>
                  ) : (
                    <>
                      Proceed to Classification
                      <ChevronRight className="ml-2 h-4 w-4" />
                    </>
                  )}
                </Button>
              )}
            </CardContent>
          </Card>
        )}

        {/* Stage 2: Classification Results */}
        {classificationResult && (
          <Card className="mb-8 border-purple-200">
            <CardHeader className="bg-purple-50/50">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Activity className="h-5 w-5 text-purple-600" />
                  <CardTitle>Stage 2: Tumor Classification</CardTitle>
                </div>
                <CheckCircle2 className="h-5 w-5 text-green-500" />
              </div>
            </CardHeader>
            <CardContent className="pt-6">
              <div className="grid md:grid-cols-3 gap-4 mb-4">
                <div>
                  <p className="text-sm text-gray-600">Tumor Type</p>
                  <p className="text-lg font-bold text-purple-600">{classificationResult.tumorType}</p>
                </div>
                <div>
                  <p className="text-sm text-gray-600">Confidence</p>
                  <p className="text-lg font-semibold">
                    {(parseFloat(classificationResult.confidence) * 100).toFixed(1)}%
                  </p>
                </div>
                <div>
                  <p className="text-sm text-gray-600">Severity</p>
                  <Badge
                    variant={classificationResult.severity === 'High' ? 'destructive' : 'default'}
                  >
                    {classificationResult.severity}
                  </Badge>
                </div>
              </div>

              {!gradcamData && (
                <Button
                  onClick={generateGradCAM}
                  disabled={loading}
                  className="bg-green-600 hover:bg-green-700"
                >
                  {loading ? (
                    <>
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                      Generating...
                    </>
                  ) : (
                    <>
                      Generate GradCAM Visualization
                      <ChevronRight className="ml-2 h-4 w-4" />
                    </>
                  )}
                </Button>
              )}
            </CardContent>
          </Card>
        )}

        {/* GradCAM Visualization */}
        {gradcamImage && (
          <Card className="mb-8 border-green-200">
            <CardHeader className="bg-green-50/50">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Brain className="h-5 w-5 text-green-600" />
                  <CardTitle>GradCAM Explainability Visualization</CardTitle>
                </div>
                <CheckCircle2 className="h-5 w-5 text-green-500" />
              </div>
              <CardDescription>
                Heatmap showing areas of focus for the AI model's decision
              </CardDescription>
            </CardHeader>
            <CardContent className="pt-6">
              <div className="bg-gray-100 rounded-lg p-4 mb-4">
                <img
                  src={gradcamImage}
                  alt="GradCAM Visualization"
                  className="w-full max-w-md mx-auto rounded-lg shadow-lg"
                />
              </div>
              <p className="text-sm text-gray-600 mb-4">
                Red/yellow areas indicate regions that strongly influenced the model's prediction.
                This helps radiologists understand the AI's reasoning.
              </p>

              {hospitals.length === 0 && (
                <Button
                  onClick={findNearbyHospitals}
                  disabled={loading}
                  className="bg-orange-600 hover:bg-orange-700"
                >
                  {loading ? (
                    <>
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                      Searching...
                    </>
                  ) : (
                    <>
                      Find Nearby Hospitals
                      <ChevronRight className="ml-2 h-4 w-4" />
                    </>
                  )}
                </Button>
              )}
            </CardContent>
          </Card>
        )}

        {/* Nearby Hospitals */}
        {hospitals.length > 0 && (
          <Card className="mb-8 border-orange-200">
            <CardHeader className="bg-orange-50/50">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <MapPin className="h-5 w-5 text-orange-600" />
                  <CardTitle>Nearby Treatment Centers</CardTitle>
                </div>
                <CheckCircle2 className="h-5 w-5 text-green-500" />
              </div>
              <CardDescription>
                Specialized hospitals for brain tumor treatment near your location
              </CardDescription>
            </CardHeader>
            <CardContent className="pt-6">
              <div className="space-y-4">
                {hospitals.map((hospital) => (
                  <div
                    key={hospital.id}
                    className="border rounded-lg p-4 hover:shadow-md transition-shadow"
                  >
                    <div className="flex justify-between items-start mb-2">
                      <div>
                        <h3 className="font-semibold text-lg">{hospital.name}</h3>
                        <p className="text-sm text-gray-600">{hospital.specialization}</p>
                      </div>
                      <Badge variant="outline">{hospital.distance}</Badge>
                    </div>
                    <p className="text-sm text-gray-700 mb-2">{hospital.address}</p>
                    <div className="flex items-center justify-between">
                      <p className="text-sm text-gray-600">{hospital.phone}</p>
                      <div className="flex items-center gap-1">
                        <span className="text-yellow-500">★</span>
                        <span className="text-sm font-medium">{hospital.rating}</span>
                      </div>
                    </div>
                  </div>
                ))}
              </div>

              {currentStage < 4 && (
                <Button
                  onClick={generateReport}
                  className="mt-6 bg-red-600 hover:bg-red-700"
                >
                  Generate Final Report
                  <ChevronRight className="ml-2 h-4 w-4" />
                </Button>
              )}
            </CardContent>
          </Card>
        )}

        {/* Report Generation */}
        {currentStage === 4 && (
          <Card className="mb-8 border-red-200">
            <CardHeader className="bg-red-50/50">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <FileText className="h-5 w-5 text-red-600" />
                  <CardTitle>Comprehensive Analysis Report</CardTitle>
                </div>
                <Button onClick={downloadReport} variant="default">
                  <Download className="h-4 w-4 mr-2" />
                  Download PDF
                </Button>
              </div>
            </CardHeader>
            <CardContent className="pt-6">
              {/* Report Content for PDF */}
              <div ref={reportRef} className="bg-white p-8 rounded-lg border">
                <div className="text-center mb-8">
                  <h1 className="text-3xl font-bold mb-2">Brain Tumor Analysis Report</h1>
                  <p className="text-gray-600">NeuroScan AI - Advanced Medical Imaging</p>
                  <Separator className="my-4" />
                </div>

                {/* Patient Info */}
                <div className="mb-6">
                  <h2 className="text-xl font-bold mb-3">Patient Information</h2>
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <p className="text-sm text-gray-600">Name:</p>
                      <p className="font-semibold">{patientName}</p>
                    </div>
                    <div>
                      <p className="text-sm text-gray-600">Age:</p>
                      <p className="font-semibold">{patientAge} years</p>
                    </div>
                    <div>
                      <p className="text-sm text-gray-600">Gender:</p>
                      <p className="font-semibold">{patientGender}</p>
                    </div>
                    <div>
                      <p className="text-sm text-gray-600">Report Date:</p>
                      <p className="font-semibold">{new Date().toLocaleDateString()}</p>
                    </div>
                  </div>
                </div>

                <Separator className="my-6" />

                {/* Detection Results */}
                <div className="mb-6">
                  <h2 className="text-xl font-bold mb-3">Stage 1: Tumor Detection</h2>
                  <div className="bg-gray-50 p-4 rounded">
                    <p className="font-semibold mb-2">
                      Result: {detectionResult?.tumorDetected ? '✓ Tumor Detected' : '✗ No Tumor'}
                    </p>
                    <p className="text-sm">
                      Confidence: {detectionResult?.confidence ? (parseFloat(detectionResult.confidence) * 100).toFixed(1) : 'N/A'}%
                    </p>
                  </div>
                </div>

                {/* Classification Results */}
                {classificationResult && (
                  <>
                    <Separator className="my-6" />
                    <div className="mb-6">
                      <h2 className="text-xl font-bold mb-3">Stage 2: Tumor Classification</h2>
                      <div className="bg-gray-50 p-4 rounded">
                        <p className="font-semibold mb-2">Type: {classificationResult.tumorType}</p>
                        <p className="text-sm mb-1">
                          Confidence: {(parseFloat(classificationResult.confidence) * 100).toFixed(1)}%
                        </p>
                        <p className="text-sm">Severity: {classificationResult.severity}</p>
                      </div>
                    </div>
                  </>
                )}

                {/* GradCAM */}
                {gradcamImage && (
                  <>
                    <Separator className="my-6" />
                    <div className="mb-6">
                      <h2 className="text-xl font-bold mb-3">GradCAM Visualization</h2>
                      <p className="text-sm text-gray-600 mb-3">
                        AI model focus areas for explainability
                      </p>
                      <img
                        src={gradcamImage}
                        alt="GradCAM"
                        className="w-64 h-64 mx-auto rounded"
                      />
                    </div>
                  </>
                )}

                {/* Hospitals */}
                {hospitals.length > 0 && (
                  <>
                    <Separator className="my-6" />
                    <div className="mb-6">
                      <h2 className="text-xl font-bold mb-3">Recommended Treatment Centers</h2>
                      {hospitals.slice(0, 3).map((hospital) => (
                        <div key={hospital.id} className="bg-gray-50 p-3 rounded mb-2">
                          <p className="font-semibold">{hospital.name}</p>
                          <p className="text-sm text-gray-600">{hospital.address}</p>
                          <p className="text-sm">{hospital.phone} • {hospital.distance}</p>
                        </div>
                      ))}
                    </div>
                  </>
                )}

                <Separator className="my-6" />

                <div className="text-sm text-gray-600">
                  <p className="font-semibold mb-2">Disclaimer:</p>
                  <p>
                    This report is generated by an AI system for demonstration purposes.
                    Always consult with qualified medical professionals for diagnosis and treatment.
                    This is not a substitute for professional medical advice.
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>
        )}
      </main>
    </div>
  );
}
